### PR TITLE
Script updates

### PR DESCRIPTION
**Pull request by daemel**
Minor updates to the following 
- directory checking earlier in the script
- TAG name update 
- alignment of KV naming with FHIR Proxy

### CODE REVIEW

**Comment by kamoclav** [comment]
You might be fixing this in the proxy script so feel free to ignore if that is the case but the keyvault default are still out of sync between the two scripts (highlighted in yellow in the screenshot)
image

**Comment by daemel** [comment]
Testing output 
Portal 
{
    "id": "/subscriptions/***
    "name": "api-fhir-13243",
    "location": "eastus",
    "tags": {
        "HealthArchitectures ": " FHIRStarter"
    },
    "properties": {
        "provisioningState": "Succeeded"
    }
}

Script
dale@Azure:~/fhir-starter/scripts$ ./deployFhirStarter.bash
Executing ./deployFhirStarter.bash...
Checking Azure Authentication...
Checking Script execution directory...

FHIR API Application deployment script...
 - Prerequisite:  Must have rights to provision Resources within the Subscription (ie Contributor)
 - Prerequisite:  Azure CLI (bash) access from the Azure Portal

The script gathers information then lets users choose to use a template or script deployment.
Users without CLI Access can use the template deployment from the templates directory in this repo.

Press Enter to continue, or Ctrl+C to exit
---
Collecting Azure Parameters (unless supplied on the command line)
Enter your subscription ID <press Enter to accept default> [***]:

This script will look for an existing resource group, otherwise a new one will be created
You can create new resource groups with the CLI using: az group create
Enter a resource group name <press Enter to accept default> [api-fhir-13243]:

If creating a *new* resource group, you need to set a location
You can lookup locations with the CLI using: az account list-locations
Azure API is currently availalbe in: East US, East US 2, North Central US, South Central US, West US, West US 2
Enter resource group location <press Enter to accept default> [eastus2]:
eastus

  Checking for existing Resource Group named [api-fhir-13243]...
  Resource Group [api-fhir-13243] not found a new Resource group will be created
---
Collecting Script Parameters (unless supplied on the command line)..
Enter your FHIR Service name <press Enter to accept default> [fhir13243]:

  Checking for exiting FHIR Service named [fhir13243] ...Warnings can be safely ignored...
WARNING: Command group 'config' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Command group 'healthcareapis service' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
  FHIR Service [fhir13243] not found, a new FHIR Service will be created

Enter a Key Vault name <press Enter to accept default> [kv-fhir13243]:

  Checking for existing Key Vault named [kv-fhir13243]...
  Script will deploy new Key Vault [kv-fhir13243] for FHIR Service [fhir13243]

Do you want to generate a Postman Environment for FHIR Service access? [y/n]:
y
---
Ready to start deployment of new FHIR Service: [fhir13243] with the following values:
Subscription ID:....................... ***
Resource Group Name:................... api-fhir-13243
 Use Existing Resource Group:.......... no
 Create New Resource Group:............ yes
Resource Group Location:............... eastus
KeyVault Name:......................... kv-fhir13243
 Use Existing Key Vault:............... no
 Create New Key Vault:................. yes
FHIR Service Client Application Name:.. ***
Generate Postman Environment:.......... yes

Please validate the settings above before continuing
Press Enter to continue, or Ctrl+C to exit
---
Starting Deployments

Creating Resource Group [api-fhir-13243] in location [eastus]
+ az group create --name api-fhir-13243 --location eastus --output none --tags 'HealthArchitectures = FHIRStarter'
---

Creating Key Vault [kv-fhir13243] in location [api-fhir-13243]
++ az keyvault create --name kv-fhir13243 --resource-group api-fhir-13243 --location eastus --tags 'HealthArchitectures = FHIRStarter' --output none
+ stepresult=
---
Deploying FHIR Service [fhir13243]
... note that warnings here are expected and can be safely ignored ...

Creating FHIR Service [fhir13243] in location [api-fhir-13243]

FHIR Service Audience set to***

FHIR Service Resource ID set to [/subscriptions/***/fhir13243]

Creating FHIR Service Client Application [fhir13243-svc-client]
FHIR Service Client Application ID is***
---
Setting FHIR Service Client Object ID
---
Saving FHIR Service Client Information (FS-name) to Key Vault [kv-fhir13243]
---
Granting FHIR Service Client Application FHIR Data Contributor Role
---
Generating Postman Environment File

The Postman environment [fhir13243.postman_environment.json] has been generated
The environment file along with the FHIR-CALLS-Sample-postman-collection.json can be used to access [fhir13243]

Download Files from Cloud Shell
https://docs.microsoft.com/en-us/azure/cloud-shell/using-the-shell-window#upload-and-download-files

Importing Postman files
https://learning.postman.com/docs/getting-started/importing-and-exporting-data/#importing-postman-data
************************************************************************************************************
Deployment of FHIR Service [fhir13243] and [fhir13243-svc-client] completed successfully
The FHIR Service Client Application can be used for OAuth2 client_credentials flow authentication to the FHIR Server
Client Credentials have been securely stored as Secrets in the Key Vault [kv-fhir13243]
The secret prefix is FS (for FHIR Service)
************************************************************************************************************
dale@Azure:~/fhir-starter/scripts$

**Comment by daemel** [comment]
> You might be fixing this in the proxy script so feel free to ignore if that is the case but the keyvault default are still out of sync between the two scripts (highlighted in yellow in the screenshot) image

That's a proxy fix - coming next

**Review by v-pbartley — APPROVED** [review]
I'm approving this PR because I'm interested in testing the script changes.

**Pull request merged**
